config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: "users/sessions",
    omniauth_callbacks: "users/omniauth_callbacks"
  }
  get 'home/about'
  root 'home#index'
  get 'home/add'
  resources :patients
  resources :doctors
  resources :appointments do
    post 'send_email_to_doctor', on: :member
    post 'send_email_to_patient', on: :member
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  get 'performance_test/empty'

  get 'performance_test/complex_haml_component'
  get 'performance_test/complex_erb_component'

  get 'performance_test/icon_from_helper'
  get 'performance_test/icon_from_gem'

  get 'performance_test/complex_haml_view'
  get 'performance_test/complex_erb_view'

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
  get 'home/old_about', to: redirect('home/about')
  # Defines the root path route ("/")
  # root "posts#index"
end

app/views/shared/_header.html.erb
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <a class="navbar-brand" href="#"><span class="text-blue-700 font-bold">Labsmart</span></a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
            <%=link_to 'Home', root_path, class:"nav-link active"%>
        </li>
        <li class="nav-item">
            <%=link_to 'Empty page', performance_test_empty_path, target: '_blank', class:"nav-link active"%>
        </li>
        <li class="nav-item">
            <%=link_to 'Haml component', performance_test_complex_haml_component_path, target: '_blank', class:"nav-link active"%>
        </li>
        <li class="nav-item">
            <%=link_to 'Erb component', performance_test_complex_erb_component_path, target: '_blank', class:"nav-link active"%>
        </li>
        <li class="nav-item">
            <%=link_to 'Haml view', performance_test_complex_haml_view_path, target: '_blank', class:"nav-link active"%>
        </li>
        <li class="nav-item">
            <%=link_to 'Erb view', performance_test_complex_erb_view_path, target: '_blank', class:"nav-link active"%>
        </li>
        <li class="nav-item">
          <%=link_to 'Icon(helpers)', performance_test_icon_from_helper_path, target: '_blank', class:"nav-link active"%>
        </li>
        <li class="nav-item">
          <%=link_to 'Icon(gem)', performance_test_icon_from_gem_path, target: '_blank', class:"nav-link active"%>
        </li>
          <% if user_signed_in? %>
          <li class="nav-item">
            <%=link_to 'Patients List', patients_path, class:"nav-link"%>
        </li>
        <li class="nav-item">
            <%=link_to 'Doctors List', doctors_path, class:"nav-link"%>
        </li>
        <li class="nav-item">
            <%=link_to 'Appointments', appointments_path, class:"nav-link"%>
        </li>
        <li class="nav-item">
            <%=button_to 'Logout', destroy_user_session_path, method: :delete,class:"nav-link"%>
        </li>
        <% if current_user.avatar_url %>
        <li class="nav-item">
            <%=image_tag current_user.avatar_url, class:"nav-link"%>
        </li>
        <%end%>
           <%else%>
           <li class="nav-item">
            <%=link_to 'Sign Up', new_user_session_path, class:"nav-link"%>
        </li>
           <% end %>
      </ul>
    </div>
  </div>
</nav>