config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: "users/sessions",
    omniauth_callbacks: "users/omniauth_callbacks"
  }
  get 'home/about'
  root 'home#index'
  get 'home/add'
  resources :patients
  resources :doctors
  resources :appointments do
    post 'send_email_to_doctor', on: :member
    post 'send_email_to_patient', on: :member
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  get 'performance_test/empty'

  get 'performance_test/complex_haml_component'
  get 'performance_test/complex_erb_component'

  get 'performance_test/icon_from_helper'
  get 'performance_test/icon_from_gem'

  get 'performance_test/complex_haml_view'
  get 'performance_test/complex_erb_view'

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
  get 'home/old_about', to: redirect('home/about')
  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/patient.rb
class Patient < ApplicationRecord
  validates :email, presence: true
  validates :first_name, presence: true
  has_many :appointments
  has_many :doctors, through: :appointments
end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_patient, only: [:show, :edit, :update, :destroy]

  def index
    @patients = Patient.all
  end

  def show
    @patient = Patient.find(params[:id])
  end

  def new
    @patient = Patient.new
  end

  def edit
  end

  def create
    @patient = Patient.new(patient_params)

    if @patient.save
      redirect_to @patient, notice: 'Patient was successfully created.'
    else
      render :new
    end
  end

  def update
    if @patient.update(patient_params)
      redirect_to @patient, notice: 'Patient was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @patient.destroy
    redirect_to patients_url, notice: 'Patient was successfully destroyed.'
  end

  private

  def set_patient
    @patient = Patient.find(params[:id])
  end

  def patient_params
    params.require(:patient).permit(:first_name, :last_name, :phone_number, :email, :disease, :age)
  end
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/views/patients/edit.html.erb
<div class="container mt-5">
  <h1 class="mb-4 text-5xl font-bold"><%= action_name.capitalize %> Patient</h1>

  <%= form_with(model: @patient, local: true, html: { class: 'needs-validation' }) do |form| %>
    <% if @patient.errors.any? %>
      <div class="alert alert-danger">
        <h4 class="alert-heading">Errors:</h4>
        <ul class="mb-0">
          <% @patient.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="mb-3">
      <%= form.label :first_name, class: 'form-label' %>
      <%= form.text_field :first_name, class: 'form-control' %>
    </div>

    <div class="mb-3">
      <%= form.label :last_name, class: 'form-label' %>
      <%= form.text_field :last_name, class: 'form-control' %>
    </div>

    <div class="mb-3">
      <%= form.label :phone_number, class: 'form-label' %>
      <%= form.text_field :phone_number, class: 'form-control' %>
    </div>

    <div class="mb-3">
      <%= form.label :email, class: 'form-label' %>
      <%= form.text_field :email, class: 'form-control' %>
    </div>

    <div class="mb-3">
      <%= form.label :disease, class: 'form-label' %>
      <%= form.text_field :disease, class: 'form-control' %>
    </div>

    <div class="mb-3">
      <%= form.label :age, class: 'form-label' %>
      <%= form.number_field :age, class: 'form-control' %>
    </div>

    <div class="mb-3">
      <%= form.submit 'Save', class: 'btn btn-primary' %>
      <%= link_to 'Back', patients_path, class: 'btn btn-secondary' %>
    </div>
  <% end %>
</div>

app/views/patients/index.html.erb
<%
  @profiler = MemoryProfilerTask.new('patient index template')
  @profiler.start
%>
<div class="p-20">
  <center>
    <h1 class="mb-10 text-5xl font-bold text-blue-700">PATIENTS</h1>
    <table class="table table-success table-striped-columns p-10">
      <thead>
        <tr>
          <th>First Name</th>
          <th>Last Name</th>
          <th>Phone Number</th>
          <th>Email</th>
          <th>Disease</th>
          <th>Age</th>
          <th colspan="3"></th>
        </tr>
      </thead>
      <tbody>
        <% @patients.each do |patient| %>
          <tr>
            <td><%= patient.first_name %></td>
            <td><%= patient.last_name %></td>
            <td><%= patient.phone_number %></td>
            <td><%= patient.email %></td>
            <td><%= patient.disease %></td>
            <td><%= patient.age %></td>
            <td><%= link_to 'Show', patient, class: "btn btn-primary" %></td>
            <td><%= link_to 'Edit', edit_patient_path(patient), class: "btn btn-secondary" %></td>
            <td><%= link_to 'Destroy', patient, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %></td>
          </tr>
        <% end %>
      </tbody>
    </table>

    <%= link_to 'Add a Patient', new_patient_path, class: "bg-blue-700 p-2 mt-10 text-white font-bold rounded-md hover:bg-blue-500" %>
  </center>
</div>
<%
  @profiler.stop_and_log
%>

app/views/patients/new.html.erb
<div class="flex items-center justify-center">
  <div class="container mt-5">
    <h1 class="mb-4 text-5xl font-bold"><%= action_name.capitalize %> Patient</h1>

    <%= form_with(model: @patient, local: true, html: { class: 'needs-validation' }) do |form| %>
      
      <% if @patient.errors.any? %>
        <div class="alert alert-danger">
          <h4 class="alert-heading">Errors:</h4>
          <ul class="mb-0">
            <% @patient.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <div class="mb-3">
        <%= form.label :first_name, class: 'form-label' %>
        <%= form.text_field :first_name, class: 'form-control' %>
      </div>

      <div class="mb-3">
        <%= form.label :last_name, class: 'form-label' %>
        <%= form.text_field :last_name, class: 'form-control' %>
      </div>

      <div class="mb-3">
        <%= form.label :phone_number, class: 'form-label' %>
        <%= form.text_field :phone_number, class: 'form-control' %>
      </div>

      <div class="mb-3">
        <%= form.label :email, class: 'form-label' %>
        <%= form.text_field :email, class: 'form-control' %>
      </div>

      <div class="mb-3">
        <%= form.label :disease, class: 'form-label' %>
        <%= form.text_field :disease, class: 'form-control' %>
      </div>

      <div class="mb-3">
        <%= form.label :age, class: 'form-label' %>
        <%= form.number_field :age, class: 'form-control' %>
      </div>

      <div class="mb-3">
        <%= form.submit 'Save', class: 'btn btn-primary' %>
        <%= link_to 'Back', patients_path, class: 'btn btn-secondary' %>
      </div>

    <% end %>
  </div>
</div>

app/views/patients/show.html.erb
<div class="flex flex-col items-center justify-center p-20">
  <h1 class="text-5xl font-bold mb-5">Patient Details</h1>

  <p>
    <strong>First Name:</strong>
    <%= @patient.first_name %>
  </p>

  <p>
    <strong>Last Name:</strong>
    <%= @patient.last_name %>
  </p>

  <p>
    <strong>Phone Number:</strong>
    <%= @patient.phone_number %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= @patient.email %>
  </p>

  <p>
    <strong>Disease:</strong>
    <%= @patient.disease %>
  </p>

  <p>
    <strong>Age:</strong>
    <%= @patient.age %>
  </p>

  <div class="flex gap-10">
    <%= link_to 'Edit', edit_patient_path(@patient), class: "btn btn-primary" %>
    <%= link_to 'Back', patients_path, class: "btn btn-secondary" %>
    
    <%= form_with(model: @patient, method: :delete, local: true) do %>
      <%= submit_tag 'Delete', class: 'btn btn-danger' %>
    <% end %>
  </div>
</div>