config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: "users/sessions",
    omniauth_callbacks: "users/omniauth_callbacks"
  }
  get 'home/about'
  root 'home#index'
  get 'home/add'
  resources :patients
  resources :doctors
  resources :appointments do
    post 'send_email_to_doctor', on: :member
    post 'send_email_to_patient', on: :member
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  get 'performance_test/empty'

  get 'performance_test/complex_haml_component'
  get 'performance_test/complex_erb_component'

  get 'performance_test/icon_from_helper'
  get 'performance_test/icon_from_gem'

  get 'performance_test/complex_haml_view'
  get 'performance_test/complex_erb_view'

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
  get 'home/old_about', to: redirect('home/about')
  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/doctor.rb
class Doctor < ApplicationRecord
  validates :first_name, presence: true
  validates :email, presence: true
  has_many :appointments
  has_many :patients, through: :appointments
end

app/controllers/doctors_controller.rb
class DoctorsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_doctor, only: [:show, :edit, :update, :destroy]

  def index
    @doctors = Doctor.all
  end

  def new
    @doctor = Doctor.new
  end

  def create
    @doctor = Doctor.new(doctor_params)
    if @doctor.save
      redirect_to root_path, notice: "Doctor was saved successfully"
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @doctor.update(doctor_params)
      redirect_to doctor_path(@doctor), notice: "Doctor was updated successfully"
    else
      render :edit
    end
  end

  def show
  end

  def destroy
    if @doctor.destroy
      redirect_to doctors_path, notice: "Deleted successfully"
    else
      redirect_to root_path, alert: "There was an error deleting the doctor"
    end
  end

  private

  def set_doctor
    @doctor = Doctor.find(params[:id])
  end

  def doctor_params
    params.require(:doctor).permit(:first_name, :last_name, :contact, :email, :degree)
  end
end

app/views/doctors/edit.html.erb
<div>
  <center>
    <%= form_with model: @doctor do |form| %>
    
      <% if form.object.errors.any? %>
        <% form.object.errors.full_messages.each do |message| %>
          <div class="alert alert-danger mt-[-300px]" role="alert">
            <%= message %>
          </div>
        <% end %>
      <% end %>

      <h1 class="text-5xl font-bold mb-10 text-blue-700">EDIT DOCTOR</h1>

      <div class="mb-5">
        <%= form.label :first_name, class: "block mb-1" %>
        <%= form.text_field :first_name, class: "border p-2" %>
      </div>

      <div class="mb-5">
        <%= form.label :last_name, class: "block mb-1" %>
        <%= form.text_field :last_name, class: "border p-2" %>
      </div>

      <div class="mb-5">
        <%= form.label :email, class: "block mb-1" %>
        <%= form.text_field :email, class: "border p-2" %>
      </div>

      <div class="mb-5">
        <%= form.label :contact, class: "block mb-1" %>
        <%= form.text_field :contact, class: "border p-2" %>
      </div>

      <div class="mb-5">
        <%= form.label :degree, class: "block mb-1" %>
        <%= form.text_field :degree, class: "border p-2" %>
      </div>

      <%= form.submit "Update Doctor", class: "bg-blue-700 p-2 mt-10 text-white font-bold rounded-md hover:bg-blue-500" %>
    
    <% end %>
  </center>
</div>

app/views/doctors/index.html.erb
<div class="p-20">
  <center>
    <h1 class="mb-10 text-5xl font-bold text-blue-700">DOCTORS</h1>
    <table class="table table-success table-striped-columns p-10">
      <thead>
        <tr>
          <th>First Name</th>
          <th>Last Name</th>
          <th>Phone Number</th>
          <th>Email</th>
          <th>DEGREE</th>
          <th colspan="3"></th>
        </tr>
      </thead>
      <tbody>
        <% @doctors.each do |doctor| %>
          <tr>
            <td><%= doctor.first_name %></td>
            <td><%= doctor.last_name %></td>
            <td><%= doctor.contact %></td>
            <td><%= doctor.email %></td>
            <td><%= doctor.degree %></td>
            <td><%=link_to 'Show', doctor, class: "btn btn-primary"%></td>
            <td><%= link_to 'Update', edit_doctor_path(doctor), class: "btn btn-secondary" %></td>
            <td><%=link_to 'Delete', doctor, method: :delete, class: "btn btn-danger"%></td>
          </tr>
        <% end %>
      </tbody>
    </table>

    <%= link_to 'Add a doctor', new_doctor_path, class: "bg-blue-700 p-2 mt-10 text-white font-bold rounded-md hover:bg-blue-500" %>
  </center>
</div>

app/views/doctors/new.html.erb
<div>
  <center>
    <%= form_with model: @doctor do |form| %>
      
      <% if form.object.errors.any? %>
        <% form.object.errors.full_messages.each do |message| %>
          <div class="alert alert-danger mt-[-300px]" role="alert">
            <%= message %>
          </div>
        <% end %>
      <% end %>

      <h1 class="text-5xl font-bold mb-10 text-blue-700">CREATE DOCTOR</h1>

      <div class="mb-5">
        <%= form.label :first_name, class: "block mb-1" %>
        <%= form.text_field :first_name, class: "border p-2" %>
      </div>

      <div class="mb-5">
        <%= form.label :last_name, class: "block mb-1" %>
        <%= form.text_field :last_name, class: "border p-2" %>
      </div>

      <div class="mb-5">
        <%= form.label :email, class: "block mb-1" %>
        <%= form.text_field :email, class: "border p-2" %>
      </div>

      <div class="mb-5">
        <%= form.label :contact, class: "block mb-1" %>
        <%= form.text_field :contact, class: "border p-2" %>
      </div>

      <div class="mb-5">
        <%= form.label :degree, class: "block mb-1" %>
        <%= form.text_field :degree, class: "border p-2" %>
      </div>

      <%= form.submit "Create Doctor", class: "bg-blue-700 p-2 mt-10 text-white font-bold rounded-md hover:bg-blue-500" %>

    <% end %>
  </center>
</div>

app/views/doctors/show.html.erb
<%=@doctor.first_name%>
<%= form_with(model: @doctor, method: :delete, local: true) do %>
  <%= submit_tag 'Delete', class: 'btn btn-danger' %>
<% end %>